# Generated by Django 5.1.4 on 2025-02-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='strengths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weaknesses',
            field=models.JSONField(default=list),
        ),
    ]
