# Generated by Django 5.1.4 on 2025-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='Subscribe to our newsletter'),
        ),
    ]
