# Generated by Django 5.1.4 on 2025-03-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.TextField(default='User has not submitted any code yet', max_length=10000),
        ),
    ]
