# Generated by Django 5.1.4 on 2025-01-07 02:02

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='name',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(default='Unnamed Group', max_length=254),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='invite_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=8, max_length=8, prefix='', unique=True),
        ),
    ]
