# Generated by Django 5.1.4 on 2025-01-11 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pg_app.question'),
        ),
    ]
