# Generated by Django 5.1.4 on 2025-01-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0002_remove_solution_name_alter_usergroup_group_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='custom_user',
        ),
    ]
