# Generated by Django 5.1.4 on 2025-02-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0002_alter_solution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='last_updated',
            field=models.CharField(default='inf', max_length=250),
        ),
    ]
