# Generated by Django 5.1.4 on 2025-01-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0002_usergroup_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='question_pool_type',
            field=models.CharField(choices=[('DAILY', 'Daily Question'), ('BLIND_75', 'Blind 75'), ('NEETCODE_150', 'Neetcode 150'), ('NEETCODE_250', 'Neetcode 250'), ('LC_ALL', 'Leetcode All'), ('CUSTOM', 'Custom Pool')], default='DAILY', max_length=36),
        ),
    ]
