# Generated by Django 5.1.4 on 2025-02-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0003_solution_attempts_solution_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='accepted',
        ),
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('has_not_started', 'Has not started'), ('in_progress', 'In progress'), ('solved', 'Solved')], default='has_not_started', max_length=28),
        ),
        migrations.AlterField(
            model_name='solution',
            name='memory',
            field=models.CharField(blank=True, default=-1, max_length=12),
        ),
        migrations.AlterField(
            model_name='solution',
            name='runtime',
            field=models.CharField(blank=True, default=-1, max_length=12),
        ),
    ]
