# Generated by Django 5.1.4 on 2025-01-13 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0003_alter_usergroup_question_pool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pg_app.question'),
        ),
    ]
