# Generated by Django 5.1.4 on 2025-01-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0003_rename_user_profile_custom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='custom_user',
            new_name='user',
        ),
    ]
