# Generated by Django 5.1.4 on 2025-01-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0004_rename_custom_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_groups',
        ),
    ]
