# Generated by Django 5.1.4 on 2025-01-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0005_alter_usergroup_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pg_app.question'),
        ),
    ]
