# Generated by Django 5.1.4 on 2025-01-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0006_alter_usergroup_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acceptance_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='pg_app.profile'),
        ),
    ]
