# Generated by Django 5.1.4 on 2025-01-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0007_profile_acceptance_rate_profile_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='pg_app.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='solved_questions',
            field=models.ManyToManyField(blank=True, to='pg_app.question'),
        ),
    ]
